name: Build pairing reset firmware

on:
  workflow_dispatch:

jobs:
  build-reset:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: build-reset.yaml
      archive_name: pairing-reset-use-only-when-needed
